/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FireButton {
        "text": string;
    }
    interface MdcDrawer {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFireButtonElement extends Components.FireButton, HTMLStencilElement {
    }
    var HTMLFireButtonElement: {
        prototype: HTMLFireButtonElement;
        new (): HTMLFireButtonElement;
    };
    interface HTMLMdcDrawerElement extends Components.MdcDrawer, HTMLStencilElement {
    }
    var HTMLMdcDrawerElement: {
        prototype: HTMLMdcDrawerElement;
        new (): HTMLMdcDrawerElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "fire-button": HTMLFireButtonElement;
        "mdc-drawer": HTMLMdcDrawerElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FireButton {
        "text"?: string;
    }
    interface MdcDrawer {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "fire-button": FireButton;
        "mdc-drawer": MdcDrawer;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fire-button": LocalJSX.FireButton & JSXBase.HTMLAttributes<HTMLFireButtonElement>;
            "mdc-drawer": LocalJSX.MdcDrawer & JSXBase.HTMLAttributes<HTMLMdcDrawerElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
